### ISSUE TITLE
WOW

### ISSUE THREAD

**Issue by zam157** [Graysonnwu/EggrollDatabase#1]
我是[EggrollPress](https://github.com/zam157/EggrollPress)的作者，更了第八期后看到有个star找到你的仓库，发现你做的比我好很多哈哈哈🤣🤣

**Comment by Graysonnwu** [comment]
> 我是[EggrollPress](https://github.com/zam157/EggrollPress)的作者，更了第八期后看到有个star找到你的仓库，发现你做的比我好很多哈哈哈🤣🤣

其实最开始就是根据你的改的🙇🏻，第一次接触vitepress，感谢你的源码~😹

**Comment by zam157** [comment]
我也是一点点摸文档找同类仓库源码参考搭建起来的😁

你做的好，做的好啊！✈️✈️  
界面美观性和完善度都比我好很多！

一起加油吧😘😘
